apiVersion: apps/v1
kind: Deployment
metadata:
  name: lease-service
  labels:
    app: lease-service
    version: "1.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lease-service
  template:
    metadata:
      labels:
        app: lease-service
        version: "1.0"
    spec:
      containers:
      - name: lease-service
        image: ghacupha/erp-lease-service:latest
        ports:
        - containerPort: 8084
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod,api-docs"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://admin:admin@jhipster-registry:8761/eureka"
        - name: SPRING_CLOUD_CONFIG_URI
          value: "http://admin:admin@jhipster-registry:8761/config"
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: erp-config
              key: database-url
        - name: SPRING_LIQUIBASE_URL
          valueFrom:
            configMapKeyRef:
              name: erp-config
              key: database-url
        - name: SECURITY_AUTHENTICATION_JWT_BASE64_SECRET
          valueFrom:
            secretKeyRef:
              name: erp-secrets
              key: jwt-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /management/health/liveness
            port: 8084
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /management/health/readiness
            port: 8084
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: lease-service
  labels:
    app: lease-service
spec:
  selector:
    app: lease-service
  ports:
  - port: 8084
    targetPort: 8084
    protocol: TCP
  type: ClusterIP
