
retention_policies:
  business_events:
    description: "Entity lifecycle and business process events"
    event_types:
      - CREATED
      - UPDATED
      - DELETED
      - PROCESSED
      - APPROVED
      - REJECTED
      - ATTACHED
      - DETACHED
      - LINKED
      - UNLINKED
    
    retention_tiers:
      hot_storage:
        duration: "30 days"
        storage_type: "SSD"
        access_pattern: "frequent"
        search_enabled: true
        description: "Recent events for active operations"
        
      warm_storage:
        duration: "90 days"
        storage_type: "SSD/HDD hybrid"
        access_pattern: "occasional"
        search_enabled: true
        description: "Recent historical events for reporting"
        
      cold_storage:
        duration: "7 years"
        storage_type: "HDD"
        access_pattern: "rare"
        search_enabled: false
        description: "Long-term storage for compliance"
        
      archive_storage:
        duration: "indefinite"
        storage_type: "S3 Glacier Deep Archive"
        access_pattern: "very rare"
        search_enabled: false
        compression: "lz4"
        encryption: "AES-256"
        description: "Permanent archival for legal requirements"
    
    legal_requirements:
      - "SOX: 7 years minimum retention"
      - "IFRS16: Asset lifecycle documentation"
      - "Local regulations: Varies by jurisdiction"

  compliance_events:
    description: "Regulatory compliance and audit assessment events"
    event_types:
      - COMPLIANCE_ASSESSED
      - VIOLATION_DETECTED
      - REMEDIATION_COMPLETED
      - AUDIT_PERFORMED
      - REPORT_GENERATED
    
    retention_tiers:
      hot_storage:
        duration: "90 days"
        storage_type: "SSD"
        access_pattern: "frequent"
        search_enabled: true
        description: "Active compliance monitoring"
        
      warm_storage:
        duration: "1 year"
        storage_type: "SSD/HDD hybrid"
        access_pattern: "regular"
        search_enabled: true
        description: "Compliance reporting period"
        
      cold_storage:
        duration: "10 years"
        storage_type: "HDD"
        access_pattern: "rare"
        search_enabled: false
        description: "Regulatory compliance history"
        
      archive_storage:
        duration: "indefinite"
        storage_type: "S3 Glacier Deep Archive"
        access_pattern: "very rare"
        search_enabled: false
        compression: "lz4"
        encryption: "AES-256"
        description: "Permanent compliance records"
    
    legal_requirements:
      - "SOX: Indefinite retention for compliance records"
      - "GDPR: 6 years for financial records"
      - "IFRS16: Asset compliance documentation"
      - "Basel III: 7 years for risk management"

  security_events:
    description: "Security-related audit and monitoring events"
    event_types:
      - AUTHENTICATION_SUCCESS
      - AUTHENTICATION_FAILURE
      - AUTHORIZATION_FAILURE
      - PRIVILEGE_ESCALATION
      - DATA_ACCESS
      - CONFIGURATION_CHANGE
      - SECURITY_VIOLATION
    
    retention_tiers:
      hot_storage:
        duration: "30 days"
        storage_type: "SSD"
        access_pattern: "frequent"
        search_enabled: true
        description: "Active security monitoring"
        
      warm_storage:
        duration: "90 days"
        storage_type: "SSD/HDD hybrid"
        access_pattern: "regular"
        search_enabled: true
        description: "Security incident investigation"
        
      cold_storage:
        duration: "3 years"
        storage_type: "HDD"
        access_pattern: "rare"
        search_enabled: false
        description: "Security audit history"
        
      archive_storage:
        duration: "7 years"
        storage_type: "S3 Glacier"
        access_pattern: "very rare"
        search_enabled: false
        compression: "lz4"
        encryption: "AES-256"
        description: "Security compliance records"
    
    legal_requirements:
      - "ISO 27001: 3 years minimum"
      - "PCI DSS: 1 year minimum"
      - "Industry standards: Varies"

  system_events:
    description: "System health and operational events"
    event_types:
      - SERVICE_STARTED
      - SERVICE_STOPPED
      - HEALTH_CHECK
      - PERFORMANCE_METRIC
      - ERROR_OCCURRED
      - INTEGRATION_EVENT
    
    retention_tiers:
      hot_storage:
        duration: "7 days"
        storage_type: "SSD"
        access_pattern: "frequent"
        search_enabled: true
        description: "Active system monitoring"
        
      warm_storage:
        duration: "30 days"
        storage_type: "SSD/HDD hybrid"
        access_pattern: "occasional"
        search_enabled: true
        description: "System troubleshooting"
        
      cold_storage:
        duration: "1 year"
        storage_type: "HDD"
        access_pattern: "rare"
        search_enabled: false
        description: "System audit history"
        
      archive_storage:
        duration: "3 years"
        storage_type: "S3 Standard-IA"
        access_pattern: "very rare"
        search_enabled: false
        compression: "gzip"
        description: "System compliance records"

archival_storage:
  providers:
    aws_s3:
      bucket_name: "erp-audit-archive"
      storage_classes:
        - name: "Standard-IA"
          use_case: "System events archive"
          cost_per_gb_month: 0.0125
          retrieval_time: "minutes"
          
        - name: "Glacier"
          use_case: "Security events archive"
          cost_per_gb_month: 0.004
          retrieval_time: "3-5 hours"
          
        - name: "Glacier Deep Archive"
          use_case: "Business and compliance events"
          cost_per_gb_month: 0.00099
          retrieval_time: "12 hours"
      
      encryption:
        type: "AES-256"
        key_management: "AWS KMS"
        key_rotation: "annual"
      
      lifecycle_rules:
        - name: "audit-events-lifecycle"
          transitions:
            - days: 30
              storage_class: "Standard-IA"
            - days: 90
              storage_class: "Glacier"
            - days: 365
              storage_class: "Glacier Deep Archive"
  
  compression:
    algorithm: "lz4"
    expected_ratio: 0.3
    verification: "checksum"
  
  metadata:
    format: "JSON"
    includes:
      - archive_id
      - original_event_count
      - compression_ratio
      - checksum_sha256
      - created_at
      - retention_period
      - legal_hold_status

purging_policies:
  automated_purging:
    enabled: true
    schedule: "daily at 02:00 UTC"
    batch_size: 10000
    
    safety_checks:
      - legal_hold_verification
      - backup_confirmation
      - retention_period_validation
      - business_approval_required: false
    
    purging_order:
      1. "System events (oldest first)"
      2. "Security events (oldest first)"
      3. "Business events (with legal review)"
      4. "Compliance events (with legal review)"
  
  manual_purging:
    approval_required: true
    approvers:
      - "Legal Team"
      - "Compliance Officer"
      - "Data Protection Officer"
    
    documentation_required:
      - "Purging justification"
      - "Legal review confirmation"
      - "Business impact assessment"
      - "Recovery procedures"
  
  emergency_purging:
    triggers:
      - "Storage capacity critical (>95%)"
      - "Legal order for data destruction"
      - "Security incident containment"
    
    approval_process:
      - "Immediate: System events"
      - "1 hour: Security events"
      - "24 hours: Business events"
      - "Legal review: Compliance events"

backup_strategy:
  backup_frequency:
    hot_storage: "continuous (streaming)"
    warm_storage: "hourly"
    cold_storage: "daily"
    archive_storage: "weekly"
  
  backup_retention:
    daily_backups: "30 days"
    weekly_backups: "12 weeks"
    monthly_backups: "12 months"
    yearly_backups: "7 years"
  
  backup_verification:
    integrity_checks: "daily"
    restore_testing: "monthly"
    disaster_recovery_testing: "quarterly"
  
  recovery_objectives:
    rto: "4 hours"  # Recovery Time Objective
    rpo: "15 minutes"  # Recovery Point Objective
    
  recovery_procedures:
    point_in_time_recovery:
      supported: true
      granularity: "1 minute"
      retention: "30 days"
    
    cross_region_recovery:
      enabled: true
      target_region: "us-west-2"
      sync_frequency: "hourly"

compliance_matrix:
  sox_compliance:
    retention_period: "7 years minimum"
    applicable_events:
      - "Financial transaction events"
      - "Access control changes"
      - "System configuration changes"
    
    requirements:
      - "Immutable audit trail"
      - "Point-in-time reconstruction"
      - "Segregation of duties tracking"
      - "Management override detection"
  
  gdpr_compliance:
    retention_period: "6 years for financial data"
    applicable_events:
      - "Personal data processing"
      - "Consent management"
      - "Data subject requests"
      - "Cross-border transfers"
    
    requirements:
      - "Right to be forgotten implementation"
      - "Data processing lawfulness tracking"
      - "Consent audit trail"
      - "Data breach notification logs"
  
  ifrs16_compliance:
    retention_period: "Asset lifecycle + 7 years"
    applicable_events:
      - "Lease accounting transactions"
      - "Asset valuation changes"
      - "Depreciation calculations"
      - "Financial statement impacts"
    
    requirements:
      - "Lease modification tracking"
      - "Discount rate changes"
      - "Asset impairment events"
      - "Disclosure requirement compliance"

export_capabilities:
  supported_formats:
    - name: "JSON"
      use_case: "API integration"
      compression: "gzip"
      
    - name: "CSV"
      use_case: "Spreadsheet analysis"
      encoding: "UTF-8"
      
    - name: "XML"
      use_case: "Regulatory submissions"
      schema_validation: true
      
    - name: "Parquet"
      use_case: "Big data analytics"
      compression: "snappy"
  
  retrieval_sla:
    hot_storage: "< 1 second"
    warm_storage: "< 10 seconds"
    cold_storage: "< 5 minutes"
    archive_storage: "< 12 hours"
  
  bulk_export:
    max_records_per_request: 1000000
    async_processing: true
    progress_tracking: true
    notification_on_completion: true

monitoring:
  storage_metrics:
    - "Storage utilization by tier"
    - "Data growth rate"
    - "Archival success rate"
    - "Retrieval performance"
    - "Purging statistics"
  
  alerts:
    - name: "Storage Capacity Warning"
      threshold: "80% of tier capacity"
      severity: "WARNING"
      
    - name: "Storage Capacity Critical"
      threshold: "95% of tier capacity"
      severity: "CRITICAL"
      
    - name: "Archival Failure"
      condition: "Failed archival jobs > 5%"
      severity: "ERROR"
      
    - name: "Retention Policy Violation"
      condition: "Data exceeds retention period"
      severity: "CRITICAL"
      
    - name: "Backup Failure"
      condition: "Backup job failure"
      severity: "CRITICAL"

cost_optimization:
  strategies:
    - "Automated tier transitions"
    - "Compression optimization"
    - "Duplicate detection and removal"
    - "Intelligent archival scheduling"
    - "Storage class optimization"
  
  cost_monitoring:
    - "Storage costs by tier"
    - "Retrieval costs"
    - "Data transfer costs"
    - "Operational costs"
  
  budgets:
    monthly_storage_budget: "$10,000"
    annual_archival_budget: "$50,000"
    emergency_retrieval_budget: "$5,000"
  
  cost_alerts:
    - threshold: "80% of monthly budget"
      action: "Notify finance team"
    - threshold: "95% of monthly budget"
      action: "Escalate to management"
    - threshold: "100% of monthly budget"
      action: "Emergency cost review"
