version: '3.3'
services:
  asset-management-service:
    image: ghacupha/erp-asset-management-service:latest
    build:
      context: ../..
      dockerfile: src/main/docker/microservices/Dockerfile.asset-management
    volumes:
      - ./logs/:/logs/
      - ./reports-directory/:/reports-directory/
      - ./generated-reports/:/generated-reports/
      - ./business-documents/:/business-documents/
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:admin@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:admin@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=${LOCAL_PG_SERVER}/${ERP_SYSTEM_PROD_DB}
      - SPRING_LIQUIBASE_URL=${LOCAL_PG_SERVER}/${ERP_SYSTEM_PROD_DB}
      - JHIPSTER_SLEEP=30
      - ERP_SYSTEM_PROD_DB=${ERP_SYSTEM_PROD_DB}
      - PG_DATABASE_PROD_USER=${PG_DATABASE_PROD_USER}
      - PG_DATABASE_PROD_PASSWORD=${PG_DATABASE_PROD_PASSWORD}
      - LOCAL_PG_SERVER=${LOCAL_PG_SERVER}
      - SECURITY_AUTHENTICATION_JWT_BASE64_SECRET=${SECURITY_AUTHENTICATION_JWT_BASE64_SECRET}
    ports:
      - "8082:8082"
    depends_on:
      - jhipster-registry
    networks:
      - erp-microservices

networks:
  erp-microservices:
    driver: bridge
