version: '3.3'
services:
  jhipster-registry:
    image: jhipster/jhipster-registry:v7.3.0
    volumes:
      - ../central-server-config:/central-config
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,api-docs
      - SPRING_SECURITY_USER_PASSWORD=admin
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/localhost-config/
    ports:
      - 8761:8761
    networks:
      - erp-microservices

  asset-management-service:
    image: ghacupha/erp-asset-management-service:latest
    build:
      context: ../..
      dockerfile: src/main/docker/microservices/Dockerfile.asset-management
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:admin@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:admin@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://erpsystem-postgresql:5432/erpSystem
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://erpsystem-postgresql:5432/erpSystem
      - JHIPSTER_SLEEP=30
    ports:
      - "8082:8082"
    depends_on:
      - jhipster-registry
      - erpsystem-postgresql
    networks:
      - erp-microservices

  financial-core-service:
    image: ghacupha/erp-financial-core-service:latest
    build:
      context: ../..
      dockerfile: src/main/docker/microservices/Dockerfile.financial-core
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:admin@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:admin@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://erpsystem-postgresql:5432/erpSystem
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://erpsystem-postgresql:5432/erpSystem
      - JHIPSTER_SLEEP=30
    ports:
      - "8083:8083"
    depends_on:
      - jhipster-registry
      - erpsystem-postgresql
    networks:
      - erp-microservices

  lease-service:
    image: ghacupha/erp-lease-service:latest
    build:
      context: ../..
      dockerfile: src/main/docker/microservices/Dockerfile.lease-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:admin@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:admin@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://erpsystem-postgresql:5432/erpSystem
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://erpsystem-postgresql:5432/erpSystem
      - JHIPSTER_SLEEP=30
    ports:
      - "8084:8084"
    depends_on:
      - jhipster-registry
      - erpsystem-postgresql
    networks:
      - erp-microservices

  depreciation-service:
    image: ghacupha/erp-depreciation-service:latest
    build:
      context: ../..
      dockerfile: src/main/docker/microservices/Dockerfile.depreciation-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:admin@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:admin@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://erpsystem-postgresql:5432/erpSystem
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://erpsystem-postgresql:5432/erpSystem
      - JHIPSTER_SLEEP=30
    ports:
      - "8085:8085"
    depends_on:
      - jhipster-registry
      - erpsystem-postgresql
    networks:
      - erp-microservices

  wip-service:
    image: ghacupha/erp-wip-service:latest
    build:
      context: ../..
      dockerfile: src/main/docker/microservices/Dockerfile.wip-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:admin@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:admin@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://erpsystem-postgresql:5432/erpSystem
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://erpsystem-postgresql:5432/erpSystem
      - JHIPSTER_SLEEP=30
    ports:
      - "8086:8086"
    depends_on:
      - jhipster-registry
      - erpsystem-postgresql
    networks:
      - erp-microservices

  reporting-service:
    image: ghacupha/erp-reporting-service:latest
    build:
      context: ../..
      dockerfile: src/main/docker/microservices/Dockerfile.reporting-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:admin@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:admin@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://erpsystem-postgresql:5432/erpSystem
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://erpsystem-postgresql:5432/erpSystem
      - SPRING_ELASTICSEARCH_REST_URIS=http://erpsystem-elasticsearch:9200
      - JHIPSTER_SLEEP=30
    ports:
      - "8087:8087"
    depends_on:
      - jhipster-registry
      - erpsystem-postgresql
      - erpsystem-elasticsearch
    networks:
      - erp-microservices

  erpsystem-postgresql:
    image: postgres:13.4
    environment:
      - POSTGRES_USER=erpSystem
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    networks:
      - erp-microservices

  erpsystem-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
      - 'discovery.type=single-node'
    networks:
      - erp-microservices

networks:
  erp-microservices:
    driver: bridge
